### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by celoewe1971** [Christian2504/SqlBuilder#1]
Please adapt OracleDatabase.cs.example to the current implementation. Thank you.

**Comment by Christian2504** [comment]
OracleDatabase.cs.example was replaced by SqlBuilderSamplesAndTests/Connectors/OracleDatabase.cs. This assures that the module is at least compilable. There is currently no other implementation and I have no means of testing it. Please supply the adapted version in a pull request.

**Comment by celoewe1971** [comment]
My mistake. The *.example files are not part of the repository. Everything is fine/ok (and working)
